Feature 1
GlebBukhanov/GlebBukhanovUVV111 pull request #2
Opened 2021-03-25 19:27 UTC by GlebBukhanov

1 API Angle
2 Написана документация к методам класса

2021-03-25 19:33 UTC, GlebBukhanov commented
Зашёл в comit, после comit and push в git extension.  Я увидел два pull request в гитхабе в браузере. Как нам объясняли на паре я нажал pull request. И мне выдало сообщение по типу нечего сравнивать. Потому я сам создал новый pull request. Дошло ли до вас мое решение и хотелось бы узнать ошибки.

2021-03-28 21:24 UTC, MarinaPaley reviewed
### Общее впечатление
_&laquo;...
    видишь, там на горе
    возвышается крест
    под ним &ndash; десяток солдат
    повиси-ка на нем,
    а когда надоест,
    возвращайся назад
    гулять по воде, гулять по воде,
    гулять по воде со мной!&raquo;_
**Илья Кормильцев.** Поэзия &ndash; Москва; Екатеринбург : Априори, 2018. &ndash; 644 c., **&laquo;Прогулки по воде&raquo;** (с. 242)

Странная работа. Странно исполнена. Странно оформлена. Чем больше общаюсь со студентами, тем больше убеждаюсь в силе приёма [`reductio ad absurdum`](https://ru.wikipedia.org/wiki/Доведение_до_абсурда) только не в логико-математической трактовке (_т. н. &laquo;доказательство от противного&raquo;_), а в житейско-бытовом &ndash; в форме [итальянской забастовки](https://ru.wikipedia.org/wiki/Итальянская_забастовка).

### Суть
1. **Главная ветка (`master` vs `main`).** У вас их _две_ (_ДВЕ, КАРЛ! ДВЕ!_), хотя в репозитории должна быть только одна. В исключительных случаях, обусловленных процессом разработки, принятым в команде может быть больше &ndash; `develop`, `release` etc (_не Ваш случай!_). У Вас коммиты и в одной (`main`, которую сгенерировал GitHub), и в другой (`mastre`, которую создал Git). ИМЕННО ПОЭТОМУ PR И НЕ ПОЛУЧАЛСЯ &ndash; ДВЕ [КОМПОНЕНТЫ СВЯЗНОСТИ](https://ru.wikipedia.org/wiki/Компонента_связности_графа), ЭТО НЕ [ДЕРЕВО](https://ru.wikipedia.org/wiki/Дерево_(теория_графов)), ЭТО ЛЕС!

    ![image](https://user-images.githubusercontent.com/26978698/112766420-5dab7800-901a-11eb-870c-5fac446d4ba6.png)

1. **Кодировка.** У Вас это [`CP-1251`](https://ru.wikipedia.org/wiki/Windows-1251), несмотря на то, что было говорено-переговорено миллион раз про то, что мы используем [`UTF-8`](https://ru.wikipedia.org/wiki/UTF-8) (лучше с учётом [`BOM`](https://ru.wikipedia.org/wiki/Маркер_последовательности_байтов)). Я осознаю, что _скорее всего_ это сделано случайно, но Вас же предупреждали &ndash; проверяйте кодировку.
1. **Сборка проекта.** Где файлы `*.sln` и `*.vcxproj`? Чтобы взаимодействовать с Вашим проектом, его требуется [_дообработать напильником_](https://lurkmore.to/Обработать_напильником). Плевать на [студию](https://visualstudio.microsoft.com/ru/vs/), где хотя бы примитивный [`makefile`](https://ru.wikipedia.org/wiki/Makefile)?
1. **Точка входа в программу (aka `main`).** Она прекрасна всем, начиная с того факта, что её просто не должно было быть на данном этапе, и заканчивая тем, что она (_по логике здорового человека_) должна жить в _отдельном файле, ~~лежащем в отдельном проекте~~_ (про последнее пока рано даже мечтать не то, что думать). [_&laquo;Но и этого им показалось мало...&raquo;_](https://ru.wikipedia.org/wiki/Массовое_убийство_в_Сонгми)
1. **~~Работо~~Жизнеспособность.** Вы вообще собирали / запускали своё творчество? Оно же даже не компилируется! `main` в заголовочном файле, [блочный оператор](https://en.cppreference.com/w/cpp/language/statements#Compound_statements) для функции `main` не закрыт.
1. **Общая шизофазия исходного кода.** 
  - Вот скажите, зачем Вам _одновременно_ понадобилось подключать и [`<cmath>`](https://en.cppreference.com/w/cpp/header/cmath) и [`<math.h>`](https://ru.wikipedia.org/wiki/Math.h)? Первое &ndash; обёртка для второго, так как второе &ndash; заголовочный файл библиотеки для языка [C](https://ru.wikipedia.org/wiki/Си_(язык_программирования)), а первое &ndash; [С++](https://ru.wikipedia.org/wiki/C%2B%2B).  _ВНЕЗАПНО! это два разных языка_
  - Определение ([`#define`](https://en.cppreference.com/w/cpp/preprocessor/replace)) [математической константы](https://docs.microsoft.com/ru-ru/cpp/c-runtime-library/math-constants?view=msvc-160) `_USE_MATH_DEFINES` должно предварять, а не быть обрамлённым директивы [`#include`](https://en.cppreference.com/w/cpp/preprocessor/include).
  - `float` vs `double` &ndash; `M_PI` трактуется как `double`, а во всём остальном коде вы оперируете типом `float`.
  - Реализация. Зачем Вам нужна реализация? Если нужна, то почему она половинчатая?

### Резюме  
 [_&laquo;Я агрессивно-позитивен...&raquo;_](https://youtu.be/MDzwbA7wZ94?t=150)
 
 Стоит внести изменения и усилить самодисциплину.

2021-03-28 21:31 UTC, MarinaPaley requested changes
Приведите, пожалуйста, проект в порядок.

2021-04-30 13:18 UTC, GlebBukhanov reviewed
Реализация первой работы

2021-04-30 13:19 UTC, merged